// <auto-generated />
using System;
using Eureka.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eureka.Persistence.Migrations
{
    [DbContext(typeof(EurekaDbContext))]
    [Migration("20260104142247_UpdateCandidateProfileDomains")]
    partial class UpdateCandidateProfileDomains
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eureka.Domain.Applications.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("JobOfferId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CandidateUserId");

                    b.HasIndex("JobOfferId1");

                    b.HasIndex("UserId");

                    b.HasIndex("JobOfferId", "CandidateUserId")
                        .IsUnique();

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Applications.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidateDocumentId");

                    b.HasIndex("ApplicationId", "CandidateDocumentId")
                        .IsUnique();

                    b.ToTable("ApplicationDocuments", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Candidates.CandidateActivityDomain", b =>
                {
                    b.Property<Guid>("CandidateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CandidateUserId", "ActivityDomainId");

                    b.HasIndex("ActivityDomainId");

                    b.ToTable("CandidateActivityDomains", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Candidates.CandidateDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateUserId");

                    b.ToTable("CandidateDocuments", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Candidates.CandidateProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commune")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("CandidateProfiles", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sector")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Siret")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Siret")
                        .IsUnique()
                        .HasFilter("[Siret] IS NOT NULL");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Companies.CompanyNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByCompanyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Urgency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByCompanyUserId");

                    b.HasIndex("CompanyId", "Status", "CreatedAt");

                    b.ToTable("company_needs", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Companies.CompanyUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "UserId")
                        .IsUnique();

                    b.ToTable("company_users", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Offers.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyNeedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByCounselorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalaryRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyNeedId")
                        .IsUnique();

                    b.HasIndex("CreatedByCounselorUserId");

                    b.HasIndex("Status", "PublishedAt");

                    b.HasIndex("CompanyId", "Status", "PublishedAt");

                    b.ToTable("job_offers", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Offers.JobOfferActivityDomain", b =>
                {
                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JobOfferId", "ActivityDomainId");

                    b.HasIndex("ActivityDomainId");

                    b.ToTable("job_offer_activity_domains", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Shared.ActivityDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("activity_domains", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Shared.InternalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId", "CreatedAt");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt");

                    b.ToTable("internal_notes", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Shared.StatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt");

                    b.ToTable("status_history", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Eureka.Domain.Applications.Application", b =>
                {
                    b.HasOne("Eureka.Domain.Candidates.CandidateProfile", "CandidateProfile")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Offers.JobOffer", "JobOffer")
                        .WithMany()
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Offers.JobOffer", null)
                        .WithMany("Applications")
                        .HasForeignKey("JobOfferId1");

                    b.HasOne("Eureka.Domain.Users.User", null)
                        .WithMany("Applications")
                        .HasForeignKey("UserId");

                    b.Navigation("CandidateProfile");

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("Eureka.Domain.Applications.ApplicationDocument", b =>
                {
                    b.HasOne("Eureka.Domain.Applications.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Candidates.CandidateDocument", "CandidateDocument")
                        .WithMany("ApplicationDocuments")
                        .HasForeignKey("CandidateDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("CandidateDocument");
                });

            modelBuilder.Entity("Eureka.Domain.Candidates.CandidateActivityDomain", b =>
                {
                    b.HasOne("Eureka.Domain.Shared.ActivityDomain", "ActivityDomain")
                        .WithMany("Candidates")
                        .HasForeignKey("ActivityDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Candidates.CandidateProfile", "CandidateProfile")
                        .WithMany("ActivityDomains")
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityDomain");

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("Eureka.Domain.Candidates.CandidateDocument", b =>
                {
                    b.HasOne("Eureka.Domain.Candidates.CandidateProfile", "CandidateProfile")
                        .WithMany("Documents")
                        .HasForeignKey("CandidateUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("Eureka.Domain.Candidates.CandidateProfile", b =>
                {
                    b.HasOne("Eureka.Domain.Users.User", "User")
                        .WithOne("CandidateProfile")
                        .HasForeignKey("Eureka.Domain.Candidates.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eureka.Domain.Companies.CompanyNeed", b =>
                {
                    b.HasOne("Eureka.Domain.Companies.Company", "Company")
                        .WithMany("Needs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Companies.CompanyUser", "CreatedByCompanyUser")
                        .WithMany("CreatedNeeds")
                        .HasForeignKey("CreatedByCompanyUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedByCompanyUser");
                });

            modelBuilder.Entity("Eureka.Domain.Companies.CompanyUser", b =>
                {
                    b.HasOne("Eureka.Domain.Companies.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Users.User", "User")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eureka.Domain.Offers.JobOffer", b =>
                {
                    b.HasOne("Eureka.Domain.Companies.Company", "Company")
                        .WithMany("JobOffers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Companies.CompanyNeed", "CompanyNeed")
                        .WithOne("JobOffer")
                        .HasForeignKey("Eureka.Domain.Offers.JobOffer", "CompanyNeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Users.User", "CreatedByCounselorUser")
                        .WithMany("JobOffersCreated")
                        .HasForeignKey("CreatedByCounselorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CompanyNeed");

                    b.Navigation("CreatedByCounselorUser");
                });

            modelBuilder.Entity("Eureka.Domain.Offers.JobOfferActivityDomain", b =>
                {
                    b.HasOne("Eureka.Domain.Shared.ActivityDomain", "ActivityDomain")
                        .WithMany("JobOffers")
                        .HasForeignKey("ActivityDomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Offers.JobOffer", "JobOffer")
                        .WithMany("ActivityDomains")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityDomain");

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("Eureka.Domain.Shared.InternalNote", b =>
                {
                    b.HasOne("Eureka.Domain.Users.User", "AuthorUser")
                        .WithMany("InternalNotesAuthored")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");
                });

            modelBuilder.Entity("Eureka.Domain.Shared.StatusHistory", b =>
                {
                    b.HasOne("Eureka.Domain.Users.User", "ChangedByUser")
                        .WithMany("StatusChanges")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("Eureka.Domain.Users.UserRole", b =>
                {
                    b.HasOne("Eureka.Domain.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eureka.Domain.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eureka.Domain.Applications.Application", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Eureka.Domain.Candidates.CandidateDocument", b =>
                {
                    b.Navigation("ApplicationDocuments");
                });

            modelBuilder.Entity("Eureka.Domain.Candidates.CandidateProfile", b =>
                {
                    b.Navigation("ActivityDomains");

                    b.Navigation("Applications");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Eureka.Domain.Companies.Company", b =>
                {
                    b.Navigation("JobOffers");

                    b.Navigation("Needs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Eureka.Domain.Companies.CompanyNeed", b =>
                {
                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("Eureka.Domain.Companies.CompanyUser", b =>
                {
                    b.Navigation("CreatedNeeds");
                });

            modelBuilder.Entity("Eureka.Domain.Offers.JobOffer", b =>
                {
                    b.Navigation("ActivityDomains");

                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Eureka.Domain.Shared.ActivityDomain", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("JobOffers");
                });

            modelBuilder.Entity("Eureka.Domain.Users.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Eureka.Domain.Users.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CandidateProfile");

                    b.Navigation("CompanyUsers");

                    b.Navigation("InternalNotesAuthored");

                    b.Navigation("JobOffersCreated");

                    b.Navigation("StatusChanges");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
